language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install python-coveralls
  - wget https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/download.sh && ./download.sh
script:
  - python -m pytest test.py --cov=c_git_info --cov-report term-missing
after_success:
  - coveralls