language: python
dist: trusty
sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install git -y
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install python-coveralls
  - wget https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh && sudo chmod +x install-powershell.sh && ./install-powershell.sh
script:
  - git --version
  - python -m pytest test.py --cov=c_git_info --cov-report term-missing
after_success:
  - coveralls
